version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:15"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "laravel-vite-plugin"
        update-types: ["version-update:semver-major"]
