name: deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{ secrets.DEPLOY_HOST != '' && secrets.DEPLOY_USER != '' && secrets.DEPLOY_PATH != '' && secrets.SSH_PRIVATE_KEY != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_pgsql
          coverage: none
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies (Composer)
        run: |
          composer install --no-interaction --no-progress --prefer-dist --no-dev
          php artisan key:generate --force || true
          php artisan config:cache || true
      - name: Install dependencies (Node) & build
        run: |
          npm ci
          npm run build
      - name: Create release archive
        run: |
          tar -czf release.tgz --exclude-vcs --exclude=storage/framework/views/*             app bootstrap config database public/build resources routes artisan composer.* package*.json vite.config.*
          ls -lh release.tgz
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copy to server
        run: |
          scp -o StrictHostKeyChecking=no release.tgz ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_PATH }}/release.tgz
      - name: Deploy on server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} <<'SSH'
          set -e
          cd "${{ secrets.DEPLOY_PATH }}"
          tar -xzf release.tgz
          rm -f release.tgz
          php artisan down || true
          php artisan migrate --force || true
          php artisan optimize:clear
          php artisan up || true
          SSH

  no-deploy:
    if: ${{ !(secrets.DEPLOY_HOST != '' && secrets.DEPLOY_USER != '' && secrets.DEPLOY_PATH != '' && secrets.SSH_PRIVATE_KEY != '' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip deploy (secrets not configured yet)
        run: |
          echo "Skipping deploy: Secrets not set. Configure DEPLOY_HOST, DEPLOY_USER, DEPLOY_PATH, SSH_PRIVATE_KEY to enable this workflow."
